create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  username text unique not null,
  password_hash text not null,
  role text not null check (role in ('admin', 'staff')),
  phone text,
  birth date,
  created_at timestamptz not null default now()
);

create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null unique,
  birth date not null,
  gender text,
  blood text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.doctors (
  id bigint generated by default as identity primary key,
  name text not null,
  specialty text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id),
  doctor_id bigint not null references public.doctors(id),
  doctor_name text,
  clinic_name text,
  appointment_date date not null,
  period text not null check (period in ('morning', 'evening')),
  appointment_time time not null,
  queue_number integer not null,
  people_ahead integer not null default 0,
  type text not null,
  status text not null default 'مؤكد',
  reminder_sent_at timestamptz,
  doctor_entered_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.appointments
  add column if not exists patient_id bigint,
  add column if not exists patient_name text,
  add column if not exists phone text,
  add column if not exists birth date,
  add column if not exists doctor_id bigint,
  add column if not exists doctor_name text,
  add column if not exists clinic_name text,
  add column if not exists appointment_date date,
  add column if not exists period text,
  add column if not exists appointment_time time,
  add column if not exists date date,
  add column if not exists time time,
  add column if not exists queue_number integer,
  add column if not exists people_ahead integer default 0,
  add column if not exists type text,
  add column if not exists status text default 'مؤكد',
  add column if not exists reminder_sent_at timestamptz,
  add column if not exists doctor_entered_at timestamptz;

create index if not exists appointments_reminders_idx
  on public.appointments (appointment_date, status, reminder_sent_at);

insert into public.users (name, username, password_hash, role)
values
  ('مدير المستوصف', 'admin', '1129e68aa2e148740af33ae8bc9e78e1:274248eaa27a6b7ceff253005c09d87a4cadb94e169b4434aa3711e98f542a83b72de086293a155cf3d72f24d183780f8347343f36a08925451377fcf2b0124e', 'admin'),
  ('سارة أحمد', 'staff', '9375b3e4d3ff728d23901031d2655343:b45c792cdb7b6fce6265954038b9dfd1606de785847047f1ffe0d24f4f098918b6db1a40204cfc282d293e718665e8320ab8e26477c0b7d103a5408f46c21e09', 'staff')
on conflict (username) do update set
  name = excluded.name,
  password_hash = excluded.password_hash,
  role = excluded.role;

insert into public.doctors (name, specialty)
select * from (values
  ('د. أحمد محمد', 'طب عام'),
  ('د. نورة خالد', 'طب الأطفال'),
  ('د. سامي عبدالله', 'الأسنان'),
  ('د. ريم العتيبي', 'نساء وولادة')
) as seed(name, specialty)
where not exists (select 1 from public.doctors);
